books/urls.py
from django.urls import path

from . import views

app_name = 'books'

urlpatterns = [
    path('', views.BookList.as_view(), name='book_list'),
    path('<int:pk>/', views.BookDetail.as_view(), name='book_detail'),
    path('add', views.BookCreate.as_view(), name='book_create'),
    path('edit/<int:pk>/', views.BookUpdate.as_view(), name='book_update'),
    path('delete/<int:pk>/', views.BookDelete.as_view(), name='book_delete'),

]

crud/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('books.urls', namespace='books')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

books/models.py
from django.db import models
from django.urls import reverse

# Create your models here.


class Book(models.Model):
    title = models.CharField(max_length=255)
    author = models.CharField(max_length=255, default='author')
    description = models.TextField(null=True, blank=True)
    image = models.ImageField(upload_to='images/', default='images/default.png')
    pages = models.DecimalField(max_digits=4, decimal_places=0)
    premiere = models.DateField(null=True, blank=True)

    def __str__(self):
        return "%s | %s" % (self.title, self.author)

    def get_absolute_url(self):
        return reverse("books:book_list")

books/forms.py
from django import forms

from .models import Book


class BookForm(forms.ModelForm):

    class Meta:
        model = Book
        fields = ('title', 'author', 'pages', 'description', 'premiere', 'image')
        ordering = ['title', 'author', 'pages', 'description', 'premiere', 'image']
        labels = {
            'title': 'title',
            'author': 'author',
            'pages': 'pages',
            'description': 'description',
            'premiere': 'premiere',
            'image': 'image'
        }

    def __init__(self, *args, **kwargs):
        super(BookForm, self).__init__(*args, **kwargs)

        self.fields['title'].widget.attrs = {
            'class': 'form-control col-4 bg-danger '
        }
        self.fields['author'].widget.attrs = {
            'class': 'form-control col-4 bg-danger',
        }
        self.fields['pages'].widget.attrs = {
            'class': 'form-control col-4 bg-danger'
        }
        self.fields['description'].widget.attrs = {
            'class': 'form-control col-4 bg-danger'
        }
        self.fields['premiere'].widget.attrs = {
            'class': 'form-control col-4 bg-danger'
        }
        self.fields['image'].widget.attrs = {
            'class': 'form-control col-4 bg-danger'
        }

books/views.py
from django.views.generic import ListView, DetailView
from django.contrib.messages.views import SuccessMessageMixin
from django.contrib.auth.mixins import PermissionRequiredMixin
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.contrib.auth.views import redirect_to_login
from django.urls import reverse_lazy
from django.shortcuts import redirect

from .models import Book
from .forms import BookForm


class UserAccessMixin(PermissionRequiredMixin):
    def dispatch(self, request, *args, **kwargs):
        if (not self.request.user.is_authenticated):
            return redirect_to_login(self.request.get_full_path(),
                                    self.get_login_url(),
                                    self.get_redirect_field_name())
        if not self.has_permission():
            return redirect('/')
        return super(UserAccessMixin, self).dispatch(request, *args, **kwargs)


class BookList(ListView):
    model = Book
    template_name = 'books/book_list.html'


class BookDetail(DetailView):
    model = Book
    template_name = 'books/book_detail.html'


class BookCreate(UserAccessMixin, CreateView, SuccessMessageMixin):
    permission_required = 'books.add_book'

    model = Book
    form_class = BookForm
    template_name = 'books/book_form.html'
    success_url = reverse_lazy('books:book_list')
    success_message = 'Book created'

"""
Fields for 'Access Mixins':
    login_url = settings.LOGIN_URL
    raise_exception = False
    redirect_field_name = REDIRECT_FIELD_NAME
    redirect_unauthenticated_users = False
"""

class BookUpdate(UserAccessMixin, UpdateView, SuccessMessageMixin):
    permission_required = 'books.change_book'

    model = Book
    template_name = 'books/book_form.html'
    form_class = BookForm
    seccess_url = reverse_lazy('books:book_list')
    success_message = 'Book updated'


class BookDelete(UserAccessMixin, DeleteView, SuccessMessageMixin):
    permission_required = 'books.delete_book'

    model = Book
    template_name = 'books/book_confirm_delete.html'
    success_url = reverse_lazy('books:book_list')
    success_message = 'Book deleted'

templates/books/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">

  <script src="https://kit.fontawesome.com/cf6097f169.js" crossorigin="anonymous"></script>
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
  <link rel='stylesheet' href="{% static 'css/style.css' %}">

  <title>{% block title %}{% endblock title %}</title>
</head>
<body class="bg-dark">
  <nav class="navbar navbar-expand-lg navbar-light bg-danger p-1">
    <div class="container-fluid">

        <a class="navbar-brand text-dark text-uppercase" href="#">crud</a>

      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarNav">

        <ul class="navbar-nav h4">
          <li class="nav-item">
            <a class="nav-link" aria-current="page" href="{% url 'books:book_list' %}">list</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'books:book_create' %}">add</a>
          </li>
        </ul>
      </div>
    </div>
  </nav>
<div class="container bg-dark text-light py-4">
  {% block content %} {% endblock content %}
</div>
</body>
</html>

templates/books/book_confirm_delete.html
{% extends 'books/base.html' %}

{% block title %}book delete{% endblock title %}


{% block content %}
<h1 class="my-4">Delete -
<small>{{ object }}</small>
</h1>
<div class="row">
<div class="col-12">
<form method="post">
{% csrf_token %}
<div class="alert alert-warning" role="alert">
Are you sure to delete {{ object }} ?
</div>
<input type="submit" class="btn btn-info" value="Yes, delete it" />
<a class="btn btn-success" href="{% url 'books:book_list' %}">No, just I've tried the delete button</a>
</form>
</div>
</div>
{% endblock %}

templates/books/book_detail.html
{% extends 'books/base.html' %}

{% block title %}book detail{% endblock title %}


{% block content %}

{{object.title}}
{% endblock content %}

templates/books/book_form.html
{% extends 'books/base.html' %}


{% block title %}{% if request.path == '/add' %}add{% else %}edit{% endif %}{% endblock title %}



{% block content %}
<div class="container">
<h1 class="my-4">{% if request.path == '/add' %} New Product {% else %} Edit {% endif %}
{% if request.path != '/add' %}<small>{{ product.name }}</small>{% endif %}
</h1>

<div class="row">
<div class="col-12">
<form method="post">
{% csrf_token %}
{% for field in form %}
<div class="form-group">
{{ field.label_tag }}
{{ field }}
</div>
{% endfor %}
<input type="submit" {% if request.path == '/add' %} value="create" {% else %} value="update" {% endif %} class="btn btn-success"/>
<a href="{% url 'books:book_list' %}"><button type="button" class="btn btn-secondary">Back</button></a>
</form>
</div>
</div>
</div>
{% endblock content %}

templates/books/book_list.html
{% extends 'books/base.html' %}

{% block title %}book list{% endblock title%}

{% block content %}
<div class="container">
    <h1 class="my-4 d-flex">
        <small>books</small>
    </h1>
    <a href="{% url 'books:book_create' %}">
        <button type="button" class="btn btn-outline-danger">
            <strong>CREATE</strong>
        </button></a><br><br>

    {% if messages %}
        {% for message in messages %}
            <div class="alert alert-success" role="alert">
                {{ message }}
            </div>
        {% endfor %}
    {% endif %}
    <div class="row">
    {% if object_list %}
        <div class="col-12 pt-4" style="overflow-x: scroll">
            <table class="table">


                {% for book in object_list %}
                <div class="text-light">
                <tr>
                    <td class="text-light"><strong>{{ book.title }}</strong></td>

                <div class="icons color-danger">
                    <td><a style="width: 40px; height: 40px;"  href="{% url 'books:book_detail' book.pk %}"><button type="button" class="btn btn-outline-danger btn-sm">READ</button></a></td>
                    <td><a style="width: 40px; height: 40px;"  href="{% url 'books:book_update' book.pk %}"><button type="button" class="btn btn-outline-danger btn-sm">UPDATE</button></a></td>
                    <td><a style="width: 40px; height: 40px;"  href="{% url 'books:book_delete' book.pk %}"><button type="button" class="btn btn-outline-danger btn-sm">DELETE</button></a></td>


                </tr>
                {% endfor %}

            </table>
        </div>
    {% else %}
    <div class="col-12">

    </div>
    {% endif %}
    </div>
  </div>

{% endblock %}